[[buildpacks]]
  id = "paketo-buildpacks/ca-certificates"
  version = "3.0.0"

[[buildpacks]]
  id = "paketo-buildpacks/watchexec"
  version = "2.8.6"

[[buildpacks]]
  id = "paketo-buildpacks/node-engine"
  version = "3.0.1"

[[buildpacks]]
  id = "paketo-buildpacks/node-start"
  version = "1.1.3"

[[buildpacks]]
  id = "paketo-buildpacks/datadog"
  version = "3.6.0"

[[buildpacks]]
  id = "paketo-buildpacks/environment-variables"
  version = "4.5.6"

[[buildpacks]]
  id = "paketo-buildpacks/image-labels"
  version = "4.5.5"
